const cards = [
  {
    id: 9,
    year: '2020-2021',
    title: 'En si bon chemin ... ',
    image: '/images/data.jpg',
    description: 'Spécialisation Data chez O\'clock!  Au menu, des requêtes SQL à faire fondre le cerveau, de la gestion de base de données poussé, et pour finir de la manipulation de données à outrence !',
    path: '',
    longDescription1: 'Après avoir passé plusieurs mois à étudier avec la pédagogie que ma fournit O\'clock, qui par ailleurs rappelons le est classé comme grande école du numérique, je m\'attaque maintenant a l\'écosysteme back-end. Mon envie d\'autonomie dans mes projets et ma curiosité font que je me suis lancé une deuxieme fois dans l\'aventure de la spécialisation ( malgré l\'intensité du rythme prévu par O\'clock).',

    longDescription2: 'Dans cette spécialisation, nous abordons plus concrètement le langage SQL, les fonctionnalitées diverses des bases de données et nous allons plus loin dans leurs utilisation. Nous utilisions en socle des ORM comme Sequelize qui nous ont permis de créer de toute pièce des projets plus ou moins basique, mais de façon completement autonome. La pédagogie inversé nous fait prendre beaucoup de recul et nous permet de mieux appréhender les difficultés rencontrés. On en a tellement bavé, qu\'on les connaient ces fichues erreurs ! Dans cette spécialisation on a pu aborder les thèmes suivants:',
    techno1: 'Approfondissement des requetes préparés',
    techno2: 'Prise en main poussé de PostgrèSQL',
    techno3: 'Découverte de Squitch pour les migrations des bases de données.',
    techno4: 'Les regex ',
    techno5: 'Redis pour la gestion de cache',

    longDescription3: `Une montée en compétence impressionnante qui se termine par un projet réalisé en équipe.
    Nous avons eu un mois, très intense pour nous coordonnées avec l'équipe Front-end pour créer les maquettes du projets, le MCD, MLD, la base données et ce qui s'en suit.`,

    longDescription4: 'Une experience qui m\'a énormement fait progresser, et qui me pousse toujours plus a dire que j\'ai trouvé ma voie.',
  },
  {
    id: 8,
    year: '2020',
    title: 'Spécialisation React  !',
    image: '/images/reactlogo.png',
    description: 'Un mois de formation intensif suivie d\'un projet à réaliser en 3 semaines. Au programme, React, Hooks, Redux, Webpack, Babel',
    longDescription1: ' Durant ce mois de formation intense, nous avons pu faire un grand tour de tout ce qui compose React. A force d\'éplucher la documentation et de tester toujours plus, nous avons pu concevoir apres ce mois de spécialisation un projet.',
    longDescription2: 'L\'apprentissage de Redux, des différentes dépendances de React, nous permet d\'apréhender beaucoup plus facilement et sereinement les single page application. Ce site est d\'ailleurs fait en React, et alimenté par redux !',
    techno1: 'POO dans toute sa splendeur',
    techno2: 'React Redux et son environnement',
    techno3: 'Sass / Scss et semantic UI react',
    techno4: 'Socket.IO, découverte des fondamentaux des webSocket',
    techno5: 'GitHub et Linux',
    path: '',
  },
  {
    id: 7,
    year: '2020',
    title: 'Renconversion en cours',
    image: '/images/oclock.png',
    description: 'Formation de 5 mois "Full-Stack JS" auprès de l\'école Oclock labelisé Grande école du numérique. Format télé-présentiel, autonomie et rigueur obligatoire.',
    longDescription1: 'Après avoir passé un bon moment a me former seul, j\'ai décidé de prendre le risque de tout quitter pour me consacrer a ce que je voulais faire.',
    longDescription2: 'Après avoir eu des difficultés dans le lancement de ma startUp, la COVID 19 ayant térassé mon envie du moment d\'entrepreunariat, j\'ai décidé de suivre mon intuition et passer le cap.',
    techno1: '5 mois de formation dédié  Javascript et ses environnements',
    techno2: 'Une formation full remote, qui m\'a données une automie de travail hors du commun',
    techno3: 'Un cursus Front et Back-end solide',
    techno4: 'La motivation d\'un changement de vie',
    techno5: '',
    longDescription3: ' Il était prévu dans un premier temps d\'integrer EPITECH Montpellier, mais la COVID19 a fait basculer de nombreuse chose, et je me suis donc tourné vers une école prestigieuse, O\'Clock. J\'y ai découvert une méthodologie de travail, acquis une rigueur de travail qui perdure au moment meme ou je créer ce site.',

    path: '',
  },
  {
    id: 6,
    year: '2019-2020',
    title: "Pourquoi s'arreter",
    image: '/images/fleach.jpg',
    description: 'Création de ma Start-up FLEACH. Logiciel SAAS dédié aux plages privées pour améliorer leurs gestion',
    longDescription1: 'Après m\'être formé dans divers domaines du numérique, j\'ai estimé que c\était le bon moment pour lancer le projet qui me tenait à coeur. ',
    longDescription2: 'La société à été créer en 2019 avec pour ambition de créer un logiciel pour facilité l\'automatisation et la gestion des plages privées, et données la possibilité à leurs clients de réserver leurs transats sur internet. J\'ai eu la chance d\'être séléctionné pour integrer un incubateur de startUp, et ai pu créer avec une équipe de développeur d\'EPITECH Montpellier, ainsi qu\'une équipe de graphiste tout un univers autour de ma marque.',
    techno1: 'Gestion de projet de grosse envergure',
    techno2: 'Management de deux équipe en meme temps ( technique et graphique)',
    techno3: 'Esprit créatif et réalisation entière des maquettes par mes soins',
    techno4: 'UI / UX adapté en fonction des besoins des plagistes et de leurs clients ( LEAN startUp )',
    techno5: 'Campagne marketing et prospection pour la commercialisation',
    longDescription3: 'Ce fut une expérience extraordinaire qui m\'a appris énormement sur moi-même, et sortie de ma zone de confort.Le lancement de l\'application était prévu Avril 2020, et comme vous le savez, nous avons été touché par la COVID, qui a completement mis a terre le projet de commercialisation, et fait perdre la plupart de mes plages test. Le projet à du être mis à l\'arret.',
    path: '',
  },
  {
    id: 5,
    year: '2019-2020',
    title: "Partager c'est encore mieux",
    image: '/images/google.jpg',
    description: 'Partenaires Google Ateliers Numérique, j\'ai pu initier en conférence des dizaines de curieux, entrepreneurs, demandeurs d\'emplois à la gestion de projets et à la découverte du numérique.',
    longDescription1: 'Ma start-up FLEACH est devenu partenaire Google Atelier Numérique en 2019.',
    longDescription2: 'J\'ai pu donc donner des conférences dans leurs locaux sur différents sujet attrayant au numérique et aux nouvelles technologies. Le plaisir de partager ses connaissances et d\'accompagner des personnes qui ont envie d\'avancer et surement aussi des envies de reconversion comme moi',
    techno1: 'Préparation de conférence de 1 ou 2 heures en fonction des dates disponibles',
    techno2: '10 à 40 personnes présente à chaque atelier',
    techno3: 'Partage des connaissances, altruisme et bienveillance avant tout',
    techno4: 'Accompagnement de plusieurs personnes en dehors de ces ateliers pour du suivis de projet jusqu\'à parfois la concrétisation',
    techno5: 'Un challenge personnel pour la prise de parole en publique',
    path: '',
  },
  {
    id: 4,
    year: '2018',
    title: 'La perseverance',
    image: '/images/workat.jpg',
    description: 'Premiers pas dans le freelance à coté de mon emploi à la sncf. L\'appel de la passion et l\'envie de tester mon réel attrait pour le milieu. Plusieurs sites réalisés, vitrine, e-commerce ( prestashop )',
    longDescription1: 'Il était temps de voir ce que j\'avais dans le ventre ! ',
    longDescription2: 'Premieres prospections de clients, premiers contrats, premieres réalisation. Des hauts, des bats, des reussites mais aussi des remises en question. Ce que je retiendrai de cette période, c\'est la retrospective sur nous meme que ça apporte. Malgré les difficultés ou les échecs, on doit se relever, se remettre en question et surtout y arriver !',
    techno1: 'Sites statiques/vitrine pour des projets de petit commerçant',
    techno2: 'Boutique E-commerce via le CMS Prestashop',
    techno3: 'Un peu de WordPress pour ma culture personnelle',
    techno4: 'Beaucoup de gestion de projet et d\'accompagnement dans la transition digital d\'une dizaine de commercant',
    techno5: 'Une experience forte, difficile, et avec un bilan plutot positif.',
    path: '',
  },
  {
    id: 3,
    year: '2018',
    title: 'Un univers exponentiel',
    image: '/images/pouce.jpg',
    description: 'Je me rend compte de tout ce qui gravite autour du developpement web. Je décide de sortir de ma zone de confort, et me forme au marketing digital, la communication et le SEO',
    longDescription1: 'L\'univers du numérique de nos jours est tellement vaste que pour se former on ne sait pas trop vers quoi se tourner. ',
    longDescription2: 'J\'ai donc décidé de me former grâces aux Ateliers Google Numérique qui m\'ont permis d\'apprénhender beaucoup de sujet. Un contenu de qualité, et jamais assez de temps pour tout apprendre. Toutes ces notions qui ne tombe pas du ciel dans lesquelles j\'ai pris enormement de plaisir à apprendre',
    techno1: 'Marketing digital et certification Google',
    techno2: 'SEO / SEA ou comment semantiquement faire rank son site sur google',
    techno3: 'L\'utilisation des réseaux sociaux pour promouvoir une marque ou un produit',
    techno4: 'Story-telling, ou l\'art de créer un univers pour sa marque ou son produit',
    techno5: 'Un résumé d\'approche commercial pour être capable de discuter et être légitime auprès de futurs clients',

    path: '',
  },
  {
    id: 2,
    year: '2017',
    title: 'Mes Premiers pas & sites',
    image: '/images/tryHard.png',
    description: 'Fort de mon experience acquis en solo via des tutos sur internet, divers livres, je me lance alors dans la réalisation de mon premier site personnel',
    longDescription1:'Et si je prenais un peu de temps pour moi pour me créer mon propre site, ca pourrait peut etre interesser des clients ?!',
    longDescription2:'Ce long chemin de traverse de passer des tutos Udemy, Youtube jusqu\'à chercher son indépendance via son propre site vitrine. Des difficultés en tout genre, des concepts encore obscure ont est loin du professionnel mais le résultat me plait bien et je suis content de pouvoir sortir quand meme quelque chose.',
    techno1: null,
    techno2: null,
    techno3: null,
    techno4: null,
    techno5: null,
    path: '',
  },

  {
    id: 1,
    year: '2015',
    title: 'Découverte du HTML & CSS',
    image: '/images/learn.jpg',
    description: "Je commençais à me poser pleins de questions, comment ca fonctionne ? l'avenir se tourne vers le numérique, pourquoi pas moi ?  ",
    techno1: null,
    techno2: null,
    techno3: null,
    techno4: null,
    techno5: null,
    path: '',
  },

];

export default cards;
