const projet = [
  {
    id: 1,
    link: 'http://ec2-52-86-71-5.compute-1.amazonaws.com:3000/',
    title: 'Meet my pet',
    image: '/images/sites/meetmypet/meetmyPet1.JPG',
    h3: 'Projet MeetMyPet',
    h4: 'Projet pour le titre professionnel',
    description: "Créationd'un site permettant aux maîtres de chiens de localiser via une carte interactive, des groupes de balade autour de chez eux.Mise a disposition d'une session utilisateur, d'un profil tournée autour de l'animal et de la possibilité de rejoindre des groupes et de discuter via une messagerie instantanée au sein du site.",
  },
  {
    id: 2,
    link: 'https://web.archive.org/web/20200805133046/https://www.fleach.com/',
    title: 'Fleach - ma plage connectée',
    image: '/images/sites/fleach/Fleach.JPG',
    h3: 'Projet de ma Start-Up',
    h4: 'Landing page de mon ancienne entreprise',
    description: "Créationd'un site permettant aux maîtres de chiens de localiser via une carte interactive, des groupes de balade autour de chez eux.Mise a disposition d'une session utilisateur, d'un profil tournée autour de l'animal et de la possibilité de rejoindre des groupes et de discuter via une messagerie instantanée au sein du site.",
  },
  {
    id: 3,
    link: 'https://workat.fr',
    title: 'WorkAt - Ma periode Freelance ',
    image: '/images/sites/workat/workat1.JPG',
    h3: 'Page vitrine de mon ancienne activité',
    h4: 'Site complémentaire à mon ancienne Start-Up',
    description: "je me suis lancé le défis de concurrencer l'un des plus gros annuaire français déja en place lors de la commercialisation de mon entreprise. Une interface utilisateur travaillé et moderne pour le plaisir des utilisateurs.",
  },
  {
    id: 4,
    link: 'https://eplage.fr',
    title: 'Eplage - l\'annuaire français des plages privées',
    image: '/images/sites/eplage/eplage.png',
    h3: 'Projet d\'annuaire francais',
    h4: 'Site complémentaire à mon ancienne Start-Up',
    description: "je me suis lancé le défis de concurrencer l'un des plus gros annuaire français déja en place lors de la commercialisation de mon entreprise. Une interface utilisateur travaillé et moderne pour le plaisir des utilisateurs.",
  },
  {
    id: 5,
    title: 'API GitHub - Trouver la meilleur API',
    image: '/images/sites/githubApi/githubapi.jpg',
    h3: 'Projet d\'annuaire francais',
    h4: 'Site complémentaire à mon ancienne Start-Up',
    description: "je me suis lancé le défis de concurrencer l'un des plus gros annuaire français déja en place lors de la commercialisation de mon entreprise. Une interface utilisateur travaillé et moderne pour le plaisir des utilisateurs.",
  },
  {
    id: 6,
    title: 'Reproduction de Twitch',
    image: '/images/sites/twitch/twitchHome.JPG',
    h3: 'Reproduction pour progresserSite de streaming',
    h4: 'Site de streaming',
    description: 'Utilisation de l\'API de Twitch. Reproduction intégrale du site web',
  },
  {
    id: 7,
    link: 'https://www.adagiocoaching.fr/',
    title: 'Adagio Coaching',
    image: '/images/sites/adagio/adagio.JPG',
    h3: 'Création du site via une maquette pour une cliente / amie',
    h4: 'Site vitrine d\'une equicoach',
    description: 'Une de mes premières réalisation pour une amie. Son activité se développant, elle souhaitait un site. J\'ai pu développer son site via la maquette qu\'elle m\'a fournit',
  },
];

export default projet;
